### PR TITLE
chore: update example tests in contribution docs

### LINKED ISSUE #85: Verify corectness of template tests
Every time that I copy-paste one of the agreed 'example tests' from the Contribution Guidelines document, my PR gets errors.

We need to verify that the template "gold standard" tests are correct.

**Link to the test templates:** https://github.com/coreruleset/documentation/blob/main/content/development/contribution_guidelines.md#positive-tests

### PR DESCRIPTION
**Pull request by theseion**
Fixes #85

### CODE REVIEW

**Review by dune73 — APPROVED** [review]

**Comment by dune73** [comment]
Looks good to me. Anything to say before merging @RedXanadu?

**Comment by RedXanadu** [comment]
Thank you for sorting this @theseion! I've only just seen this.

One question: what is "uri: "/post""? That looks new to me, and I don't know what it is. We don't have it documented, as far as I can see.

**Comment by theseion** [comment]
`httpbin` has one dedicated endpoint for each HTTP method. Requests to `/` return status `200` but include a large HTML payload. Using the dedicated endpoints does not include any HTML and is thus preferable in terms of raw test throughput. Yes, that should be documented.

**Comment by theseion** [comment]
See #92.

**Comment by dune73** [comment]
Thanks for explanation and doc PR.

**Pull request merged**
