### PR TITLE
chore: update regex-assembly docs

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Comment by dune73** [comment]
Thank you. This looks good. Also mostly easy to understand despite the complexity.

1-2 comments.

## regex_assembly.md: Suffix Marker

The example does too much stuff implicitly. How does it concatename to `[c-d]` and how does it replace `\W`.

## Processor Marker

This would take a full example to become transparent. It's quite unclear as it stands.

## Nesting

Please show the resulting regex. 

## Typo: store the outpur of a block

## Typo:  alternation of accepted HTTP headers: -> alternation of accepted HTTP methods:

**Comment by theseion** [comment]
@dune73 thanks! You should really start using the review feature of GH though. You can make inline suggestions to the code :)

**Comment by theseion** [comment]
> To work around this issue, the following exclude file can be used:

What did you mean to say here?

> Processor Marker

I don't think an example would help much here (I'll be happy to add one, if you think otherwise). That section is mainly there for specification purposes. If I were to read the documentation, I would skim the examples in the following sections, where the examples are tied to specific processors (which are all still unknown in `Processor Marker`).

You're right, more concrete examples would help. I'll add those in a separate PR.

**Comment by dune73** [comment]
The "work around the issue" was a copy / paste mistake. It can be ignored. Sorry.

I see your point with the Processor Marker - and I thought the same when reading it - but my problem was that I did not really grasp it and then I felt like I did not understand the subsequent sections / examples. If you can, please think of a very simple example that can be understood on it's on, even if it is not useful in practice. Just to illustrate the conceptual description you are giving.

I might have to adopt to the review feature, but it breaks the unity of the conversation for me. I really prefer to have everything on a single page. With the review feature things get split and torn apart, sometimes separate threads, etc. I see how it can be useful, but it gives me the creeps (as a side note: I write my journal file in vim, it's a text file with 19 years of notes. Unity of conversation is kind of important to me).

**Comment by theseion** [comment]
Does that help?

**Comment by dune73** [comment]
Yes, that does help. Please add the resulting regex and I'd be happy to merge.

**Comment by theseion** [comment]
I'm pretty sure that you don't want to see the output of that expression in the documentation:

```
c[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?o[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?m[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?m[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?a[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?n[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?d[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?[1-2]|([\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c??[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?:[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?([\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c??[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?:[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?n[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?e[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?s[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?t[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?e[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?d[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?1[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?2[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?\][\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?)[\"'\)\[-\x5c]*(?:(?:(?:\|\||&&)[\s\v]*)?\$[!#\(\*\-0-9\?-@_a-\{]*)?\x5c?)
```

**Comment by theseion** [comment]
I really tried to make it as simple as possible. But since it has no real meaning I don't think it makes sense to show the output. Anything more meaningful would become too complex quickly.

**Comment by dune73** [comment]
You have a point there. I'm not deep into this to realize what the processor really means and what it leads to. Then let's simply add a remark along the lines of ~ the example is there for the sake of having an example and that the generated complex regex is without any meaning, so it's not part of the documentation.

**Comment by dune73** [comment]
Thank you. Merging now.

**Pull request merged**
