### PR TITLE
Extended the engine and integration options

### PR DESCRIPTION
**Pull request by dune73**
I've extended this quite a bit. Please review carefully before merging.

@fzipi: I have taken on some of your text, but may have dropped some of it as well. Please check.

@RedXanadu: Please review (-> expand and refine) the mentioning of LoadBalancer.org. I did this so Kemp was not the only listing in this category. Well thinking of, I could also add AVI...

### CODE REVIEW

**Review by RedXanadu — COMMENTED** [review]
Excellent expansion to the engine and integration page.

I've made some suggested amendments in a PR. Apologies that the commit history is a bit messy: Git was convinced there was a merge conflict until I manually copy-pasted the content into GitHub… I think it's resolved now, though.

**Comment by dune73** [comment]
Thanks @RedXanadu. Where can I find your PR?

**Comment by RedXanadu** [comment]
Sorry, yes, it would help if I included a link… https://github.com/dune73/crs-documentation/pull/1

**Comment by RedXanadu** [comment]
@fzipi Are you okay with these changes/expansions to your original content?

I think this is good to go, unless there are any objections :slightly_smiling_face:

**Comment by fzipi** [comment]
I'm more than good. Happy to see we are getting this in good shape.

**Pull request merged**
