### PR TITLE
Implement British-American English test

### PR DESCRIPTION
**Pull request by RedXanadu**
Upload a list of British English-specific spellings and create a GitHub
Action to test all content (under content/) for any British English
spellings.

### CODE REVIEW

**Comment by RedXanadu** [comment]
This took a bit of tweaking to make work… but now it works, and it even prints a neat little summary if the check fails:

```
****************************** Offending Matches *******************************
content/configuring/paranoia_levels.md:emphasised
content/configuring/paranoia_levels.md:behaviour
content/_index.md:defence
content/_index.md:Licence
content/deployment/engine_integration_options.md:flavours
content/deployment/install.md:behaviour
Error: Process completed with exit code 1.
```

**Comment by dune73** [comment]
Nice one. That's the clean approach.

The failing tests are due to the ideal of adding new tests?

**Comment by RedXanadu** [comment]
@dune73 This PR failed its own test because it found a bunch of British English spellings :)

I've just pushed an extra commit which addresses the found spellings. Spelling test is now passing.

Ready to merge, I think!

**Comment by dune73** [comment]
Let's merge, then. Thank you!

**Pull request merged**
