### PR TITLE
Issue #94: Adds 'HAProxy Technologies' as a commercial WAF appliance vendor

### PR DESCRIPTION
**Pull request by NickMRamirez**

### CODE REVIEW

**Comment by NickMRamirez** [comment]
Not a problem. I put our boilerplate marketing text in, but it makes sense now why that wouldn't be appropriate. How does this updated text look?

```
### HAProxy Technologies

HAProxy Technologies embeds ModSecurity v3 in three of its products via the Libmodsecurity module. 
ModSecurity is included with: HAProxy Enterprise, HAProxy ALOHA, and HAProxy Enterprise Kubernetes
Ingress Controller. 

To learn more, visit the [HAProxy WAF solution page on haproxy.com](https://www.haproxy.com/solutions/web-application-firewall).
```

**Comment by dune73** [comment]
Thank you for your understanding @NickMRamirez.

This sounds good to me. 

@RedXanadu: Anything to add? Otherwise feel free to merge.

**Comment by RedXanadu** [comment]
Thank you both! This looks perfect @NickMRamirez, thanks for your work on this. Merging now!

@dune73 As we get more vendors and options appearing, we should agree on an ordering. Maybe alphabetical, or sponsors first and then the rest alphabetical. A conversation for another day :slightly_smiling_face:

**Comment by dune73** [comment]
Good thinking. I thought that would be a question sooner or later. But now much pressure from integrators to be listed so far.

**Pull request merged**
