### PR TITLE
Flag outdated content for readers

### PR DESCRIPTION
**Pull request by RedXanadu**
This PR adds a note to the top of each page which has not been rewritten/updated/checked yet, so that readers know which parts of the documentation can currently be relied on to be up to date and accurate.

### CODE REVIEW

**Comment by RedXanadu** [comment]
@dune73 Because the rewriting process is taking some time, I propose to flag each page of documentation that has not yet been rewritten/updated/checked with a note, so that readers know what content can and cannot be relied upon to be accurate and up to date:

> **The content on this page may be outdated.** We are currently in the process of rewriting all of our documentation: please bear with us while we update our older content.

Are you okay with that plan?

**Comment by dune73** [comment]
I think this is a good plan. Thanks. And sorry for not reacting earlier.

Do you have a plan when we start to link /docs better on the website, also rewrite the primary Documentation page on the website?

**Comment by RedXanadu** [comment]
I think, once we are confident that the new documentation is properly ready we should start to push it and link it wherever we can. Also, we should then rewrite the main Documentation page on coreruleset.org, as you suggest.

I'm starting rewriting the CONTRIBUTING.MD/Developers docs now… so hopefully the docs will be in a better and more complete shape soon!

**Comment by RedXanadu** [comment]
Merging PR.

**Comment by dune73** [comment]
Thank you. Sounds good.

**Pull request merged**
