### PR TITLE
Rework rule exclusion content

### PR DESCRIPTION
**Pull request by RedXanadu**
This PR massively reworks the rule exclusion content, adds a significant amount of content, and adds lots of examples.

### CODE REVIEW

**Comment by fzipi** [comment]
I see you are getting comfortable at hugo by now! :D Excellent job!

**Review by fzipi — APPROVED** [review]
LGTM!

**Comment by dune73** [comment]
Great contribution.

He are some things that spring to mind:

* www.mywordpressblog.com actually resolves to a chinese blog. Maybe use example.com
* The indentation is puzzling for the alert. This is a rarely seen format and thus not familiar with the reader. It might even be better to leave it without the CRs and simply highlight the rule ID and the message.
* I suggest you expand the Alert Fatigue section to include _sensitive information in logs_ and potentially mention GDPR on top
* "When working in blocking mode" -> better: "When working in strict blocking mode" (Working in blocking mode with high anomaly threshold is no problem usually)
* "This table is available as a well presented, downloadable Rule Exclusion Cheatsheet at netnea.com" Would you mind adding my name here too (like below). Netnea is rather irrelevant and can be removed here.
* "Directly Modifying CRS Rules" : I'd close this section that there are alternative ways of dealing with FPs that are only slightly more difficult - but do not pose any problems during updates.
* "even entire rule categories." I'd add a remark in brackets "(identified by a tag or a range of rule IDs)"
* Matrix with the 4 rule exclusion types: Maybe add a box where you explain there is also a RemoveByMsg, but that it's use is dicouraged because messages can be dynamic and dealing with special characters is hard and error prone.
* Tags: I think you need to explain which tags are useful for rule exclusions and which ones are not. I would not do any REs on the CAPEC tags, but categories like `attack_sqli` generally do qualify. Also good to explain when you would do via tag and when via range.
* Example 3: I suggest to pick up the var name from the "Example False Positive"
* Example 4: You should describe the use of a regex here. Also maybe further above that this options exists (and where it exists).
* Example 6: "(Runtime RE. Exclude entire rule.)" that's wrong
* I like the fact that you came up with a realistic scenario and 8 examples in total
* "It’s possible to write a conditional ..." It's probably useful to give the hint that these additional constrains can be chained into the same rule.
* "customisations" is a candidate for the UK-English dictionary

**Comment by RedXanadu** [comment]
@dune73 Thank you for the thorough feedback!

I agree with, and have implemented, all of the changes proposed apart from one:

> "Example 6: "(Runtime RE. Exclude entire rule.)" that's wrong"

I'm not certain I understand your point. Is it that the text says "Exclude entire rule" and the rule itself is dealing with a rule _category_, not a _single rule_?

**Comment by dune73** [comment]
Thanks for the fixes.

And yes, it's a removal by tag while the description says "entire rule". Looks like copy&paste from example 5 to me.

**Comment by RedXanadu** [comment]
A-hah, yes, I see what you mean.

For the 8 examples, I was using the first line, e.g. "_(Runtime RE. Exclude entire rule.)_", to indicate which quadrant of the matrix the example was from. So, one of either "Configure-time RE" or "Runtime RE", plus either "Exclude entire rule" or "Exclude specific variable from rule".

I kept the category as "Exclude entire rule" to keep it simple, but it's not 100% correct, as you point out. Do you think the category should instead be titled "Exclude entire rule/tag"?

**Comment by RedXanadu** [comment]
@dune73 I've modified the descriptions of the examples which work with tags, e.g.:

_Example 6 (ctl:ruleRemoveByTag)
(Runtime RE. Exclude entire tag.)_

and modified the descriptions to be "Exclude the entire rule/tag" and "Exclude a specific variable from the rule/tag". The descriptions and explanations are slightly longer now, but also more accurate.

I think this is good to go, now.

**Comment by dune73** [comment]
This sounds very good. Thank you for this big contribution. Merging now.

**Pull request merged**
