### PR TITLE
docs: update sandbox options

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

- add blocking mode docs
- add in/out anomaly score threshold docs
- moved all options to lowercase for coherence

### CODE REVIEW

**Comment by dune73** [comment]
Thank you.

I like the lowercasing of the options.

### question 1

Why do you talk about an omitted / default value, when `json-matched-rules` is the default? Am I getting this wrong?

### question 2

The threshold values do not make much sense unless you are in blocking mode. You may want to indicate that in the description.

**Comment by fzipi** [comment]
1. that was already there. I just moved it to the first line instead of the last line. But definitely outputs are different:
```shell
❯ curl -H 'x-crs-mode: blocking' -H 'x-crs-inbound-anomaly-score: 9' -H 'x-crs-paranoia-level: 4' -H 'x-format-output: json-matched-rules' -H 'x-backend: nginx' https://sandbox.coreruleset.org/anything\?id=alias%20j%3Da%3B%20c%24jt
```

Gives you:

```json
[{"message":"Invalid character in request (outside of very strict set)","paranoia_level":"4","id":"920273"},{"message":"Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)","paranoia_level":"4","id":"942432"},{"message":"Inbound Anomaly Score Exceeded (Total Score: 8)","paranoia_level":"1","id":"949110"}]
```

And

```bash
❯ curl -H 'x-crs-mode: blocking' -H 'x-crs-inbound-anomaly-score: 9' -H 'x-crs-paranoia-level: 4' -H 'x-backend: nginx' https://sandbox.coreruleset.org/anything\?id=alias%20j%3Da%3B%20c%24jt
``` 

Gives you:

```json
{"transaction":{"client_ip":"172.23.0.7","time_stamp":"Tue Jul 19 17:26:23 2022","server_id":"18ef9df0535ddbc9bf7e758945720948ef22a843","client_port":35040,"host_ip":"172.23.0.6","host_port":80,"unique_id":"fbe7f08d78507e17ec1ea2c9cbba5c2c","request":{"method":"GET","http_version":1.1,"uri":"/anything?id=alias%20j%3Da%3B%20c%24jt","headers":{"X-Real-IP":"201.217.153.162","Host":"localhost","Connection":"close","User-Agent":"curl/7.79.1","Accept":"*/*","x-backend":"nginx","x-crs-mode":"blocking","x-crs-inbound-anomaly-score":"9","x-crs-paranoia-level":"4"}},"response":{"body":"<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.20.2</center>\r\n</body>\r\n</html>\r\n","http_code":403,"headers":{"Server":"nginx/1.20.2","Date":"Tue, 19 Jul 2022 17:26:23 GMT","Content-Length":"153","Content-Type":"text/html","Connection":"close","X-Unique-ID":"fbe7f08d78507e17ec1ea2c9cbba5c2c"}},"producer":{"modsecurity":"ModSecurity v3.0.7 (Linux)","connector":"ModSecurity-nginx v1.0.3","secrules_engine":"Enabled","components":["OWASP_CRS/4.0.0-rc1\""]},"messages":[{"message":"Invalid character in request (outside of very strict set)","details":{"match":"Matched \"Operator `ValidateByteRange' with parameter `38,44-46,48-58,61,65-90,95,97-122' against variable `ARGS:id' (Value: `alias j=a; c$jt' )","reference":"o5,1o9,1o10,1o12,1v17,15t:urlDecodeUni","ruleId":"920273","file":"/etc/modsecurity.d/owasp-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf","lineNumber":"1596","data":"ARGS:id=alias j=a; c$jt","severity":"2","ver":"OWASP_CRS/4.0.0-rc1","rev":"","tags":["modsecurity","application-multi","language-multi","platform-multi","attack-protocol","OWASP_CRS","capec/1000/210/272","paranoia-level/4"],"maturity":"0","accuracy":"0"}},{"message":"Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)","details":{"match":"Matched \"Operator `Rx' with parameter `((?:[~!@#\\$%\\^&\\*\\(\\)\\-\\+=\\{\\}\\[\\]\\|:;\\\"'´’‘`<>][^~!@#\\$%\\^&\\*\\(\\)\\-\\+=\\{\\}\\[\\]\\|:;\\\"'´’‘`<>]*?){2})' against variable `ARGS:id' (Value: `alias j=a; c$jt' )","reference":"o7,3o7,3v17,15t:urlDecodeUni","ruleId":"942432","file":"/etc/modsecurity.d/owasp-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf","lineNumber":"1758","data":"Matched Data: =a; found within ARGS:id: alias j=a; c$jt","severity":"4","ver":"OWASP_CRS/4.0.0-rc1","rev":"","tags":["modsecurity","application-multi","language-multi","platform-multi","attack-sqli","OWASP_CRS","capec/1000/152/248/66","PCI/6.5.2","paranoia-level/4"],"maturity":"0","accuracy":"0"}},{"message":"Inbound Anomaly Score Exceeded (Total Score: 8)","details":{"match":"Matched \"Operator `Ge' with parameter `5' against variable `TX:BLOCKING_INBOUND_ANOMALY_SCORE' (Value: `8' )","reference":"","ruleId":"949110","file":"/etc/modsecurity.d/owasp-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf","lineNumber":"176","data":"","severity":"0","ver":"OWASP_CRS/4.0.0-rc1","rev":"","tags":["modsecurity","anomaly-evaluation"],"maturity":"0","accuracy":"0"}}]}}%
```

So one is raw audit log (the default), and the json matches are only the matches.

2. Sure.

**Comment by fzipi** [comment]
@dune73 Anything else you can think to add/remove here?

**Comment by fzipi** [comment]
@dune73 ping

**Comment by fzipi** [comment]
As the default behavior now is `blocking`, I've updated the documentation about it.

**Pull request merged**
