### PR TITLE
feat(k8s): add nginx ingress documentation

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Based on comments in the slack channel, added this short k8s guidance.

### CODE REVIEW

**Comment by RedXanadu** [comment]
I should have time to review this tomorrow (Monday 30 May).

**Comment by dune73** [comment]
Having very little k8s knowhow, this addresses my needs in an adequate way. I can now understand how this works and what it's meant to do.

More detail, would be useful but it's OK to postpone this to some future date.

What I think would be useful is to note that this is based on nginx / ModSec3 and therefore comes with all the downsides of said platform.

Question: What keeps anybody from publishing an Apache Ingress controller and why does not that gain any traction?

**Comment by fzipi** [comment]
About your question: people find "simpler" to use nginx, to some extent. I highly doubt there is going to ever be anything similar. There is apache apisix that you can use, which... is based on nginx.

Apache is not going to gain new adepts, despite being rock solid and quite comparable on speed.

**Comment by dune73** [comment]
No, probably not, but I was never sure if there was some magic sauce that Apache lacked and Nginx had that made it better suited. But all I hear now is that Nginx ingress has developed into the standard while nobody made the investment to configure an on-par Apache alternative. Which is a bit sad, but I guess, that's the way it is then.

**Comment by RedXanadu** [comment]
Apologies, I didn't get time to look at this today as I'd hoped. I'll take a look soon.

**Review by RedXanadu — COMMENTED** [review]
Sorry @fzipi, not until today did I manage to find time to look at this.

Great content! Sure to attract a lot of traffic.

I've made some tweaks to the language and tone (but not the technical content) at:
https://github.com/coreruleset/documentation/pull/56/files

Please let me know if you're happy with those amendments.

**Comment by RedXanadu** [comment]
Amendments approved and merged.

Thanks again for writing this page @fzipi.

Merging.

**Pull request merged**
