### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by RedXanadu**
PR makes the changes requested in [CRS PR New contributing.md #2487](https://github.com/coreruleset/coreruleset/pull/2487).

- Clarification about EOL and EOF.
- Testing content added.

### CODE REVIEW

**Comment by RedXanadu** [comment]
@fzipi Here is the draft content on "Writing Tests".

How does it look? This is a good time to nitpick, as the example positive and negative tests may be copy-pasted by future contributors (so we should make sure they are perfect!)

**Review by fzipi — APPROVED** [review]
Very well done! Thanks a lot!

**Comment by fzipi** [comment]
Maybe we can add a [link to the yaml format](https://github.com/coreruleset/ftw/blob/main/docs/YAMLFormat.md) in the `Writing tests` part...

**Comment by RedXanadu** [comment]
Oops, that wasn't quite ready yet. We were 60 seconds out of sync, there :laughing: 

I made one more commit after I realised FTW and Go-FTW weren't linked…

**Comment by RedXanadu** [comment]
Fixed in #35.

**Pull request merged**
