### PR TITLE
fix: temp remove matomo

### PR DESCRIPTION
**Pull request by fzipi**
## what

- remove matomo

## why

- fixing documentation indent

⚠️ This is a workaround, not a fix for [#205.](https://github.com/coreruleset/website/issues/205)

### CODE REVIEW

**Comment by fzipi** [comment]
It is just a temporary fix. If you have time to fix the real problem, then please do.

**Comment by dune73** [comment]
Is there an issue for the real problem?

**Comment by fzipi** [comment]
https://github.com/coreruleset/website/issues/205

**Comment by theseion** [comment]
It looks to me like the issue is actually with the theme. I can't test it right now because I would need to install an older version of hugo, but checking out an older version but keeping the newest theme version shows the same issue back to July. The them had a 7.0.0 release on October 13, that could be the issue.

**Comment by fzipi** [comment]
Well, then if we don't plan to merge let's close.

**Pull request closed without merging**
